# -*- coding: utf-8 -*-

# Roque absolute paths
"""
FILE_NAME3D = "/home/rocko/Documents/Tesis/dataset/Heart/3D/im_t1.mhd"
DATASET_PATH = "/home/rocko/Documents/Tesis/dataset/Heart/2D"
SLICE_FILENAME = "2d_im_t"
OUTPUT_PATH = "/home/rocko/Documents/Tesis/dataset/registracion"
ANALISIS_PATH = "/home/rocko/Documents/Tesis/analisis"
PYRAMID_PATH = "/home/rocko/Desktop/Tesis/pyramid"
NSOLUTION_PATH = "/home/rocko/Desktop/Tesis/Nsolutions"
NSOLUTION_RESULTS_FILENAME = "results.txt"
NSOLUTION_INITIALS_FILENAME = "initials.txt"
DISCRETE = "discrete"
CONTINUOUS = "continuous"
GROUND_TRUTH_FILENAME = "groundTruthTransformations.csv"
INDIVIDUAL_TEST_PATH = "/home/rocko/Desktop/Tesis/IndividualTests"
SERIAL_TEST_PATH = "/home/rocko/Desktop/Tesis/SerialTests"

# Franco absolute paths
"""
# FILE_NAME3D = "/home/franco/Escritorio/Tesis/dataset/Heart/3D/im_t1.mhd"
# OUTPUT_PATH = "/home/franco/Escritorio/Tesis/dataset/registracion"
# DATASET_PATH = "/home/franco/Escritorio/Tesis/dataset/Heart/2D"
# SLICE_FILENAME = "2d_im_t"
# ANALISIS_PATH = "/home/franco/Escritorio/Tesis/analisis"
# PYRAMID_PATH = "/home/franco/Escritorio/Tesis/pyramid"
# NSOLUTION_RESULTS_FILENAME = "results.txt"
# NSOLUTION_INITIALS_FILENAME = "initials.txt"
# DISCRETE = "discrete"
# CONTINUOUS = "continuous"
# REFINED = "refined"
# GROUND_TRUTH_FILENAME = "groundTruthTransformations.csv"
# INDIVIDUAL_TEST_PATH = "/home/franco/Escritorio/Tesis/IndividualTests"
# SERIAL_TEST_PATH = "/home/franco/Escritorio/Tesis/SerialTests"


FILE_NAME3D = "./dataset_basico/volumen/im_t1.mhd"
OUTPUT_PATH = "./dataset_basico/registration"
DATASET_PATH = "./dataset_basico/slices"
SLICE_FILENAME = "2d_im_t"
ANALISIS_PATH = "./analisis"
PYRAMID_PATH = "./pyramid"
NSOLUTION_RESULTS_FILENAME = "results.txt"
NSOLUTION_INITIALS_FILENAME = "initials.txt"
DISCRETE = "discrete"
CONTINUOUS = "continuous"
REFINED = "refined"
GROUND_TRUTH_FILENAME = "groundTruthTransformations.csv"
INDIVIDUAL_TEST_PATH = "./IndividualTests"
SERIAL_TEST_PATH = "./SerialTests"